#!/usr/bin/env python

import socket
import sys

# Handle Connection to Server
sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
server_address = ('localhost', 8080)
sock.connect(server_address)

# Handle file to be read on remote server
try:
    input_file = sys.argv[1]
except:
    print("Please enter file to be tailed as argument")
    exit()
sock.sendall(input_file)

# Handle output from remote server
try:
    while True:
        data = sock.recv(1024)
        print(data)
        # Ensure that output is flushed
        sys.stdout.flush()
finally:
    sock.close()
    